// Admin auth primitives (single-admin, no users table):
//  - password check against the ADMIN_PASSWORD_HASH secret (PBKDF2-SHA256,
//    generated by `npm run admin:hash`),
//  - stateless session cookie: `exp.nonce.hmac` signed with SESSION_SECRET,
//  - CSRF token derived from the same session (extra belt over SameSite=Strict).
// All crypto is WebCrypto (Workers-native); comparisons are constant-time.

const SESSION_TTL_SECONDS = 7 * 24 * 60 * 60; // 7 days
export const SESSION_COOKIE = "rn_admin";

// ── password hash ────────────────────────────────────────────────────────────
// Format: pbkdf2$<iterations>$<saltB64>$<hashB64>  (see scripts/admin-hash.mjs)

export async function verifyPassword(
  password: string,
  stored: string,
): Promise<boolean> {
  const parts = stored.split("$");
  if (parts.length !== 4 || parts[0] !== "pbkdf2") return false;
  const iterations = Number(parts[1]);
  if (!Number.isFinite(iterations) || iterations < 1000) return false;
  let salt: Uint8Array, want: Uint8Array;
  try {
    salt = b64decode(parts[2]);
    want = b64decode(parts[3]);
  } catch {
    return false;
  }

  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(password),
    "PBKDF2",
    false,
    ["deriveBits"],
  );
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", hash: "SHA-256", salt: salt as BufferSource, iterations },
    key,
    want.length * 8,
  );
  return timingSafeEqualBytes(new Uint8Array(bits), want);
}

// ── session token ────────────────────────────────────────────────────────────

export interface Session {
  exp: number; // epoch seconds
  nonce: string;
}

export async function createSessionToken(secret: string): Promise<string> {
  const exp = Math.floor(Date.now() / 1000) + SESSION_TTL_SECONDS;
  const nonce = b64urlEncode(crypto.getRandomValues(new Uint8Array(9)));
  const sig = await hmacB64url(secret, `sess:${exp}:${nonce}`);
  return `${exp}.${nonce}.${sig}`;
}

export async function verifySessionToken(
  secret: string,
  token: string | undefined,
): Promise<Session | null> {
  if (!token) return null;
  const parts = token.split(".");
  if (parts.length !== 3) return null;
  const [expStr, nonce, sig] = parts;
  const exp = Number(expStr);
  if (!Number.isFinite(exp) || exp < Date.now() / 1000) return null;
  const want = await hmacB64url(secret, `sess:${exp}:${nonce}`);
  if (!timingSafeEqualStr(sig, want)) return null;
  return { exp, nonce };
}

// CSRF token bound to the session (rotates with each login).
export async function csrfToken(secret: string, s: Session): Promise<string> {
  return hmacB64url(secret, `csrf:${s.exp}:${s.nonce}`);
}

export async function verifyCsrf(
  secret: string,
  s: Session,
  presented: string | undefined,
): Promise<boolean> {
  if (!presented) return false;
  return timingSafeEqualStr(presented, await csrfToken(secret, s));
}

// Cookie serialization. Path=/admin keeps the cookie off the public site
// entirely; SameSite=Strict blocks cross-site sends (CSRF layer 1).
export function sessionCookie(token: string): string {
  return `${SESSION_COOKIE}=${token}; Max-Age=${SESSION_TTL_SECONDS}; Path=/admin; HttpOnly; Secure; SameSite=Strict`;
}

export function clearSessionCookie(): string {
  return `${SESSION_COOKIE}=; Max-Age=0; Path=/admin; HttpOnly; Secure; SameSite=Strict`;
}

export function readCookie(header: string | undefined, name: string): string | undefined {
  if (!header) return undefined;
  for (const part of header.split(/;\s*/)) {
    const idx = part.indexOf("=");
    if (idx === -1) continue;
    if (part.slice(0, idx) === name) return part.slice(idx + 1);
  }
  return undefined;
}

// ── crypto helpers ───────────────────────────────────────────────────────────

async function hmacB64url(secret: string, message: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign(
    "HMAC",
    key,
    new TextEncoder().encode(message),
  );
  return b64urlEncode(new Uint8Array(sig));
}

function timingSafeEqualStr(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

function timingSafeEqualBytes(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}

function b64urlEncode(bytes: Uint8Array): string {
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function b64decode(s: string): Uint8Array {
  const bin = atob(s.replace(/-/g, "+").replace(/_/g, "/"));
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}
