-- Sample seed (NOT a migration). Apply with: npm run seed:local
-- Everything here is clearly labelled sample content: 6 short articles, 4 categories,
-- 7 tags, 1 topic cluster and 3 AI-persona authors. Covers are generated SVG
-- placeholders (node scripts/gen-covers.mjs, then node scripts/upload-r2.mjs).
-- Replace all of it with your own content before launch.

DELETE FROM posts_tags;
INSERT INTO posts_fts(posts_fts) VALUES('delete-all'); -- contentless FTS5: cannot DELETE
DELETE FROM topic_cluster_spokes;
DELETE FROM topic_clusters;
DELETE FROM posts;
DELETE FROM tags;
DELETE FROM categories;
DELETE FROM authors;

INSERT INTO authors (id, slug, name, role, short_bio, bio, location, joined, twitter, website, expertise, featured_in, avatar_key, post_count) VALUES
  (1, 'desk-habits', 'Desk: Habits (AI persona)', 'AI-assisted sample persona', 'An AI-assisted sample persona that covers habit building and routines.', 'Desk: Habits is a sample persona, not a real person. Articles under this byline are AI-assisted demonstration content for the template and are meant to be replaced with your own editorial voice.', NULL, NULL, NULL, NULL, '["Habits","Routines","Sleep"]', '[]', NULL, 2),
  (2, 'desk-focus', 'Desk: Focus (AI persona)', 'AI-assisted sample persona', 'An AI-assisted sample persona that covers focus and attention.', 'Desk: Focus is a sample persona, not a real person. Articles under this byline are AI-assisted demonstration content for the template and are meant to be replaced with your own editorial voice.', NULL, NULL, NULL, NULL, '["Deep work","Attention","Digital minimalism"]', '[]', NULL, 2),
  (3, 'desk-systems', 'Desk: Systems (AI persona)', 'AI-assisted sample persona', 'An AI-assisted sample persona that covers planning and note-taking systems.', 'Desk: Systems is a sample persona, not a real person. Articles under this byline are AI-assisted demonstration content for the template and are meant to be replaced with your own editorial voice.', NULL, NULL, NULL, NULL, '["Planning","Note-taking","Workflows"]', '[]', NULL, 2);

INSERT INTO categories (id, slug, name, tagline, description, position, is_active, post_count, meta_title, meta_description, og_image_key) VALUES
  (1, 'habits', 'Habits', 'Small actions, steady results.', 'How routines form, why they stick, and how to design them around real life.', 1, 1, 1, 'Habit Building Guides', 'Practical guides to building routines that last.', NULL),
  (2, 'focus', 'Focus', 'Protect your attention.', 'Ways to work with fewer interruptions and more intent.', 2, 1, 2, 'Focus and Attention', 'Practical guides to deep work and attention.', NULL),
  (3, 'wellbeing', 'Wellbeing', 'Rest is part of the work.', 'Sleep, recovery, and calm routines for everyday energy.', 3, 1, 1, 'Wellbeing Guides', 'Simple, everyday routines for better rest and energy.', NULL),
  (4, 'systems', 'Systems', 'Fewer decisions, clearer weeks.', 'Planning and note-taking methods you can keep using.', 4, 1, 2, 'Planning and Note-Taking Systems', 'Lightweight planning and note-taking systems that hold up.', NULL);

INSERT INTO tags (id, slug, name, description, usage_count) VALUES
  (1, 'habits', 'Habits', 'How small repeated actions turn into routines.', 1),
  (2, 'focus', 'Focus', 'Directing attention on purpose.', 2),
  (3, 'sleep', 'Sleep', 'Evening routines and rest.', 1),
  (4, 'planning', 'Planning', 'Weekly planning and scheduling.', 1),
  (5, 'note-taking', 'Note-taking', 'Capturing and reusing what you learn.', 1),
  (6, 'digital-minimalism', 'Digital minimalism', 'Using technology with intent.', 1),
  (7, 'routines', 'Routines', 'Repeatable sequences that reduce decisions.', 2);

INSERT INTO posts
  (id, slug, category_id, author_id, title, excerpt, processed_html, reading_time, word_count,
   published_at, last_updated_at, meta_title, meta_description, schema_json, cover_image_key, cover_image_alt,
   cover_blurhash, is_featured, is_evergreen, view_count)
VALUES
  (1, 'building-habits-that-last', 1, 1, 'Building Habits That Last: Start Smaller Than Feels Useful', 'Sample article. A sample guide to making a new habit small, obvious and easy to repeat, so it survives a busy week.', '<p>Most new habits fail for a simple reason: the first version is too big. A promise to exercise for an hour, write for two hours, or meditate every morning asks for a lot of energy before the routine has any momentum. The fix is to make the first version almost embarrassingly small.</p><h2>Shrink the behavior</h2><p>Pick one action you can finish in under two minutes. Put on running shoes. Write one sentence. Open the notebook. The goal at this stage is not results but repetition. A habit is a pattern your brain learns by seeing it happen again and again, and a small action can be repeated on your worst day.</p><p>Once the small version feels automatic, add a little more. If you added too much and skipped a day, step back to the smaller version without drama.</p><h2>Attach it to a cue</h2><p>A cue is the thing that tells you it is time. The easiest cues are things you already do every day: pouring coffee, brushing your teeth, closing your laptop. Use a simple sentence to link them: after I pour my coffee, I will write one line in my journal.</p><p>Place the tools where you will see them. A book on the pillow beats a book on a shelf in another room.</p><h2>Track lightly and forgive misses</h2><p>A calendar with a mark for each completed day is enough. The point of tracking is feedback, not punishment. If you miss one day, treat it as data and resume the next day. Two misses in a row is the signal to make the habit smaller again.</p><div class="takeaways"><h3>Key takeaways</h3><ul><li>Make the first version small enough to do on a bad day.</li><li>Attach the habit to something you already do.</li><li>Track with a simple mark and resume quickly after a miss.</li></ul></div><h2>Frequently asked questions</h2><h3>How long does a habit take to form?</h3><p>It varies a lot between people and behaviors. Focus on repetition rather than a fixed number of days.</p><h3>What if I keep forgetting?</h3><p>Move the cue or the tools so they are harder to miss, and pick a cue that happens every day.</p><p><em>This is sample content created to demonstrate the template. It is not professional advice.</em></p>', 2, 367,
   '2026-09-28T08:00:00Z', '2026-09-28T08:00:00Z', 'Building Habits That Last', 'How to shrink a new habit, attach it to an existing cue, and keep it going through busy weeks.', '{"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": [{"@type": "Question", "name": "How long does a habit take to form?", "acceptedAnswer": {"@type": "Answer", "text": "It varies a lot between people and behaviors. Focus on repetition rather than a fixed number of days."}}, {"@type": "Question", "name": "What if I keep forgetting?", "acceptedAnswer": {"@type": "Answer", "text": "Move the cue or the tools so they are harder to miss, and pick a cue that happens every day."}}]}', 'uploads/posts/building-habits-that-last/cover.svg', 'Abstract gradient with geometric shapes', NULL, 1, 1, 1200),
  (2, 'a-practical-guide-to-deep-work', 2, 2, 'A Practical Guide to Deep Work Without Rearranging Your Life', 'Sample article. A sample guide to protecting one or two focused blocks a day, even when your calendar is crowded.', '<p>Deep work is time spent on a demanding task without switching to something else. You do not need a cabin or a free schedule to practice it. You need a short block, a clear target, and a way to keep interruptions out.</p><h2>Choose one block</h2><p>Look at your week and pick a single block of 60 to 90 minutes, ideally when your energy is highest. For many people that is the first part of the morning. Put the block in your calendar like a meeting with yourself and decline anything that overlaps.</p><h2>Define the target in one sentence</h2><p>Before the block starts, write what done looks like: draft the introduction, fix the three failing tests, outline the proposal. A vague task invites drifting. A concrete target gives your attention somewhere to land.</p><h2>Remove easy exits</h2><p>Close the tabs you do not need. Silence notifications on your phone and leave it in another room if you can. Keep a scratch page open for stray thoughts so you can write them down and return to the task instead of acting on them.</p><h2>End with a shutdown note</h2><p>When the block ends, spend two minutes writing where you stopped and what comes next. This small step makes the next session easier to start, and it lets you leave the work behind without worrying about losing your place.</p><div class="takeaways"><h3>Key takeaways</h3><ul><li>One protected block beats a plan for entire focused days.</li><li>Write a one-sentence target before you begin.</li><li>Make distraction harder than work, then leave a note for next time.</li></ul></div><h2>Frequently asked questions</h2><h3>How long should a deep work block be?</h3><p>Start with 60 minutes. Extend it only if you can stay engaged without strain.</p><h3>What if I work in an open office?</h3><p>Use headphones, a visible do-not-disturb sign, or book a quiet room for your block.</p><p><em>This is sample content created to demonstrate the template. It is not professional advice.</em></p>', 1, 316,
   '2026-09-26T08:00:00Z', '2026-09-26T08:00:00Z', 'A Practical Guide to Deep Work', 'Protect one or two focused blocks a day with a simple setup, a clear target and a shutdown ritual.', '{"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": [{"@type": "Question", "name": "How long should a deep work block be?", "acceptedAnswer": {"@type": "Answer", "text": "Start with 60 minutes. Extend it only if you can stay engaged without strain."}}, {"@type": "Question", "name": "What if I work in an open office?", "acceptedAnswer": {"@type": "Answer", "text": "Use headphones, a visible do-not-disturb sign, or book a quiet room for your block."}}]}', 'uploads/posts/a-practical-guide-to-deep-work/cover.svg', 'Abstract gradient with geometric shapes', NULL, 1, 1, 950),
  (3, 'a-calmer-evening-routine', 3, 1, 'A Calmer Evening Routine for Better Sleep', 'Sample article. A sample evening routine built from three small steps: dim, wind down, and prepare tomorrow.', '<p>A good night often begins hours before bedtime. An evening routine does not need to be long or elaborate. It only needs to tell your body that the day is ending, and to remove the small worries that keep you awake.</p><h2>Dim and slow down</h2><p>About an hour before bed, lower the lights in the rooms you use and switch to lamps if you can. Bright overhead light keeps your body in daytime mode. Keep the same bedtime window most days, including weekends, within an hour or so, because a regular schedule helps your body expect sleep.</p><h2>Step away from the feed</h2><p>Pick a time to put your phone on its charger outside the bedroom. If you use it as an alarm, a cheap alarm clock solves that. The goal is not to be perfect but to give yourself at least thirty minutes without scrolling before lights out.</p><h2>Prepare tomorrow in five minutes</h2><p>Write down the three things that matter tomorrow and set out what you need: clothes, a bag, the first document you will open. Moving these decisions out of your head and onto paper lowers the late-night loop of thinking about tomorrow.</p><p>Finish with something quiet that you enjoy, such as reading a few pages of a printed book, light stretching, or a warm shower.</p><div class="takeaways"><h3>Key takeaways</h3><ul><li>Dim the lights an hour before bed.</li><li>Keep your phone away from the bed.</li><li>Write tomorrow''s top three to clear your head.</li></ul></div><h2>Frequently asked questions</h2><h3>What if I cannot fall asleep after a routine?</h3><p>Get up, do something quiet in low light, and return when you feel sleepy. If sleep problems persist, speak to a health professional.</p><h3>Do I need to do every step?</h3><p>No. Start with one step and add others when it feels easy.</p><p><em>This is sample content created to demonstrate the template. It is not professional advice.</em></p>', 1, 309,
   '2026-09-24T08:00:00Z', '2026-09-24T08:00:00Z', 'A Calmer Evening Routine', 'Three small steps to wind down in the evening: dim the lights, step away from screens, and prepare tomorrow.', '{"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": [{"@type": "Question", "name": "What if I cannot fall asleep after a routine?", "acceptedAnswer": {"@type": "Answer", "text": "Get up, do something quiet in low light, and return when you feel sleepy. If sleep problems persist, speak to a health professional."}}, {"@type": "Question", "name": "Do I need to do every step?", "acceptedAnswer": {"@type": "Answer", "text": "No. Start with one step and add others when it feels easy."}}]}', 'uploads/posts/a-calmer-evening-routine/cover.svg', 'Abstract gradient with geometric shapes', NULL, 1, 1, 800),
  (4, 'plan-your-week-in-thirty-minutes', 4, 3, 'Plan Your Week in Thirty Minutes', 'Sample article. A sample weekly planning session: review, choose three priorities, and place them on the calendar.', '<p>A weekly plan keeps urgent tasks from crowding out important ones. It does not have to be a big ritual. Thirty minutes at the same time each week is enough to start the week with a clear picture of what matters.</p><h2>Review the last week (10 minutes)</h2><p>Open your calendar and task list. Note what you finished, what slipped, and why. Look for patterns, such as meetings that always run over or tasks that stay on the list for weeks. Move or delete anything that no longer matters.</p><h2>Choose three priorities (10 minutes)</h2><p>Write down the three outcomes that would make the week a success. Be specific enough that you will know when each one is done. Three is a useful limit because it forces trade-offs, and you can always add small tasks around them.</p><h2>Place them on the calendar (10 minutes)</h2><p>Give each priority a block of time, and add a buffer after meetings and travel. Leave open space on purpose, because surprises arrive every week. If a priority does not fit, shrink it or move it, rather than squeezing it between other commitments.</p><p>On each morning, take one minute to check the plan and adjust if needed.</p><div class="takeaways"><h3>Key takeaways</h3><ul><li>Hold the review at the same time every week.</li><li>Limit yourself to three priorities.</li><li>Put priorities on the calendar and keep buffers.</li></ul></div><h2>Frequently asked questions</h2><h3>When is the best time for a weekly review?</h3><p>Choose a quiet time such as Friday afternoon or Sunday evening, whichever you will actually keep.</p><h3>What tools do I need?</h3><p>A calendar and a simple list are enough. Use whatever you already have.</p><p><em>This is sample content created to demonstrate the template. It is not professional advice.</em></p>', 1, 283,
   '2026-09-22T08:00:00Z', '2026-09-22T08:00:00Z', 'Plan Your Week in Thirty Minutes', 'A simple thirty-minute weekly review that ends with three priorities placed on your calendar.', '{"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": [{"@type": "Question", "name": "When is the best time for a weekly review?", "acceptedAnswer": {"@type": "Answer", "text": "Choose a quiet time such as Friday afternoon or Sunday evening, whichever you will actually keep."}}, {"@type": "Question", "name": "What tools do I need?", "acceptedAnswer": {"@type": "Answer", "text": "A calendar and a simple list are enough. Use whatever you already have."}}]}', 'uploads/posts/plan-your-week-in-thirty-minutes/cover.svg', 'Abstract gradient with geometric shapes', NULL, 0, 1, 700),
  (5, 'note-taking-that-you-reuse', 4, 3, 'Note-Taking That You Actually Reuse', 'Sample article. A sample approach to notes: capture quickly, rewrite in your own words, and review on a schedule.', '<p>Many people collect notes and never open them again. Notes become useful when they are easy to capture, easy to find, and written in a form you can act on. A few small habits make that far more likely.</p><h2>Capture first, organize later</h2><p>Keep one inbox for quick notes, such as a single app or a pocket notebook. Do not stop to decide where something belongs. Once a day or a few times a week, empty the inbox and move each item to the right place or delete it.</p><h2>Rewrite in your own words</h2><p>Copying a quote is quick but passive. After reading something, write two or three sentences explaining it as if to a friend, and add one question or one way you could use it. This step takes a minute and is where most of the learning happens.</p><h2>Link notes to projects</h2><p>Organize by what you are working on instead of by topic. A note filed under a current project has a reason to be opened. Add a short title that states the idea, such as Shorter meetings need a written agenda, rather than a vague label.</p><h2>Review on a schedule</h2><p>Set a recurring ten-minute review each week. Skim recent notes, pull out any tasks, and archive what you no longer need. A small, regular review keeps the system useful without turning it into a hobby.</p><div class="takeaways"><h3>Key takeaways</h3><ul><li>Use one inbox and sort it on a schedule.</li><li>Rewrite ideas in your own words.</li><li>File notes by project and give them clear titles.</li></ul></div><h2>Frequently asked questions</h2><h3>Should I use paper or an app?</h3><p>Use whichever you will carry and open daily. Both can work well.</p><h3>How many notes is too many?</h3><p>If you cannot find what you need in a minute, prune and simplify your structure.</p><p><em>This is sample content created to demonstrate the template. It is not professional advice.</em></p>', 1, 311,
   '2026-09-20T08:00:00Z', '2026-09-20T08:00:00Z', 'Note-Taking That You Reuse', 'Capture quickly, rewrite in your own words, and link notes to projects so they get used.', '{"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": [{"@type": "Question", "name": "Should I use paper or an app?", "acceptedAnswer": {"@type": "Answer", "text": "Use whichever you will carry and open daily. Both can work well."}}, {"@type": "Question", "name": "How many notes is too many?", "acceptedAnswer": {"@type": "Answer", "text": "If you cannot find what you need in a minute, prune and simplify your structure."}}]}', 'uploads/posts/note-taking-that-you-reuse/cover.svg', 'Abstract gradient with geometric shapes', NULL, 0, 1, 650),
  (6, 'a-gentle-start-to-digital-minimalism', 2, 2, 'A Gentle Start to Digital Minimalism', 'Sample article. A sample guide to using technology on purpose: audit your apps, change defaults, and set simple limits.', '<p>Digital minimalism is the practice of choosing the tools that serve your goals and letting the rest go. You do not have to delete everything or move to a flip phone. Small changes to how you use your devices can free up a surprising amount of attention.</p><h2>Audit what you use</h2><p>For one week, notice which apps you open and how you feel afterward. Many devices show screen-time reports. Mark each app as useful, neutral, or draining. Remove the draining ones from your home screen, or uninstall them for a trial period of two weeks.</p><h2>Change the defaults</h2><p>Turn off notifications that are not from a person. Move social apps off the first screen. Switch the display to grayscale in the evening if your device allows it. Each change adds a little friction to mindless checking and takes a few minutes to set up.</p><h2>Set simple boundaries</h2><p>Choose one or two screen-free times, such as meals and the first half hour of the morning. Charge your phone away from the bed. Replace the habit with something specific, like a short walk or a few pages of a book, so the gap does not feel empty.</p><p>After a few weeks, add back only the tools that earn their place.</p><div class="takeaways"><h3>Key takeaways</h3><ul><li>Audit apps by how they make you feel.</li><li>Turn off notifications from non-people.</li><li>Pick one or two screen-free times and replace them with something specific.</li></ul></div><h2>Frequently asked questions</h2><h3>Do I have to quit social media?</h3><p>No. You can keep it while limiting when and how you use it.</p><h3>How long should a trial last?</h3><p>Two to four weeks is enough to see how you feel without a given app.</p><p><em>This is sample content created to demonstrate the template. It is not professional advice.</em></p>', 1, 293,
   '2026-09-18T08:00:00Z', '2026-09-18T08:00:00Z', 'A Gentle Start to Digital Minimalism', 'Audit your apps, change a few defaults, and set simple boundaries to use technology on purpose.', '{"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": [{"@type": "Question", "name": "Do I have to quit social media?", "acceptedAnswer": {"@type": "Answer", "text": "No. You can keep it while limiting when and how you use it."}}, {"@type": "Question", "name": "How long should a trial last?", "acceptedAnswer": {"@type": "Answer", "text": "Two to four weeks is enough to see how you feel without a given app."}}]}', 'uploads/posts/a-gentle-start-to-digital-minimalism/cover.svg', 'Abstract gradient with geometric shapes', NULL, 0, 1, 600);

INSERT INTO posts_tags (post_id, tag_id) VALUES
  (1, 1),
  (1, 7),
  (2, 2),
  (3, 3),
  (3, 7),
  (4, 4),
  (5, 5),
  (6, 6),
  (6, 2);

INSERT INTO topic_clusters (id, slug, name, description, pillar_keyword, hub_post_id, is_active, position) VALUES
  (1, 'building-a-calm-routine', 'Building a Calm Routine', 'Sample cluster: small habits and routines that make the day calmer.', 'calm routine', 1, 1, 1);

INSERT INTO topic_cluster_spokes (cluster_id, post_id, position) VALUES
  (1, 3, 1), (1, 4, 2), (1, 6, 3);

-- Populate the FTS index (contentless: rowid = posts.id; body is plain text).
INSERT INTO posts_fts (rowid, title, excerpt, body) VALUES
  (1, 'Building Habits That Last: Start Smaller Than Feels Useful', 'A sample guide to making a new habit small, obvious and easy to repeat, so it survives a busy week.', 'Most new habits fail for a simple reason: the first version is too big. A promise to exercise for an hour, write for two hours, or meditate every morning asks for a lot of energy before the routine has any momentum. The fix is to make the first version almost embarrassingly small. Shrink the behavior Pick one action you can finish in under two minutes. Put on running shoes. Write one sentence. Open the notebook. The goal at this stage is not results but repetition. A habit is a pattern your brain learns by seeing it happen again and again, and a small action can be repeated on your worst day. Once the small version feels automatic, add a little more. If you added too much and skipped a day, step back to the smaller version without drama. Attach it to a cue A cue is the thing that tells you it is time. The easiest cues are things you already do every day: pouring coffee, brushing your teeth, closing your laptop. Use a simple sentence to link them: after I pour my coffee, I will write one line in my journal. Place the tools where you will see them. A book on the pillow beats a book on a shelf in another room. Track lightly and forgive misses A calendar with a mark for each completed day is enough. The point of tracking is feedback, not punishment. If you miss one day, treat it as data and resume the next day. Two misses in a row is the signal to make the habit smaller again. Key takeaways Make the first version small enough to do on a bad day. Attach the habit to something you already do. Track with a simple mark and resume quickly after a miss. Frequently asked questions How long does a habit take to form? It varies a lot between people and behaviors. Focus on repetition rather than a fixed number of days. What if I keep forgetting? Move the cue or the tools so they are harder to miss, and pick a cue that happens every day. This is sample content created to demonstrate the template. It is not professional advice.'),
  (2, 'A Practical Guide to Deep Work Without Rearranging Your Life', 'A sample guide to protecting one or two focused blocks a day, even when your calendar is crowded.', 'Deep work is time spent on a demanding task without switching to something else. You do not need a cabin or a free schedule to practice it. You need a short block, a clear target, and a way to keep interruptions out. Choose one block Look at your week and pick a single block of 60 to 90 minutes, ideally when your energy is highest. For many people that is the first part of the morning. Put the block in your calendar like a meeting with yourself and decline anything that overlaps. Define the target in one sentence Before the block starts, write what done looks like: draft the introduction, fix the three failing tests, outline the proposal. A vague task invites drifting. A concrete target gives your attention somewhere to land. Remove easy exits Close the tabs you do not need. Silence notifications on your phone and leave it in another room if you can. Keep a scratch page open for stray thoughts so you can write them down and return to the task instead of acting on them. End with a shutdown note When the block ends, spend two minutes writing where you stopped and what comes next. This small step makes the next session easier to start, and it lets you leave the work behind without worrying about losing your place. Key takeaways One protected block beats a plan for entire focused days. Write a one-sentence target before you begin. Make distraction harder than work, then leave a note for next time. Frequently asked questions How long should a deep work block be? Start with 60 minutes. Extend it only if you can stay engaged without strain. What if I work in an open office? Use headphones, a visible do-not-disturb sign, or book a quiet room for your block. This is sample content created to demonstrate the template. It is not professional advice.'),
  (3, 'A Calmer Evening Routine for Better Sleep', 'A sample evening routine built from three small steps: dim, wind down, and prepare tomorrow.', 'A good night often begins hours before bedtime. An evening routine does not need to be long or elaborate. It only needs to tell your body that the day is ending, and to remove the small worries that keep you awake. Dim and slow down About an hour before bed, lower the lights in the rooms you use and switch to lamps if you can. Bright overhead light keeps your body in daytime mode. Keep the same bedtime window most days, including weekends, within an hour or so, because a regular schedule helps your body expect sleep. Step away from the feed Pick a time to put your phone on its charger outside the bedroom. If you use it as an alarm, a cheap alarm clock solves that. The goal is not to be perfect but to give yourself at least thirty minutes without scrolling before lights out. Prepare tomorrow in five minutes Write down the three things that matter tomorrow and set out what you need: clothes, a bag, the first document you will open. Moving these decisions out of your head and onto paper lowers the late-night loop of thinking about tomorrow. Finish with something quiet that you enjoy, such as reading a few pages of a printed book, light stretching, or a warm shower. Key takeaways Dim the lights an hour before bed. Keep your phone away from the bed. Write tomorrow''s top three to clear your head. Frequently asked questions What if I cannot fall asleep after a routine? Get up, do something quiet in low light, and return when you feel sleepy. If sleep problems persist, speak to a health professional. Do I need to do every step? No. Start with one step and add others when it feels easy. This is sample content created to demonstrate the template. It is not professional advice.'),
  (4, 'Plan Your Week in Thirty Minutes', 'A sample weekly planning session: review, choose three priorities, and place them on the calendar.', 'A weekly plan keeps urgent tasks from crowding out important ones. It does not have to be a big ritual. Thirty minutes at the same time each week is enough to start the week with a clear picture of what matters. Review the last week (10 minutes) Open your calendar and task list. Note what you finished, what slipped, and why. Look for patterns, such as meetings that always run over or tasks that stay on the list for weeks. Move or delete anything that no longer matters. Choose three priorities (10 minutes) Write down the three outcomes that would make the week a success. Be specific enough that you will know when each one is done. Three is a useful limit because it forces trade-offs, and you can always add small tasks around them. Place them on the calendar (10 minutes) Give each priority a block of time, and add a buffer after meetings and travel. Leave open space on purpose, because surprises arrive every week. If a priority does not fit, shrink it or move it, rather than squeezing it between other commitments. On each morning, take one minute to check the plan and adjust if needed. Key takeaways Hold the review at the same time every week. Limit yourself to three priorities. Put priorities on the calendar and keep buffers. Frequently asked questions When is the best time for a weekly review? Choose a quiet time such as Friday afternoon or Sunday evening, whichever you will actually keep. What tools do I need? A calendar and a simple list are enough. Use whatever you already have. This is sample content created to demonstrate the template. It is not professional advice.'),
  (5, 'Note-Taking That You Actually Reuse', 'A sample approach to notes: capture quickly, rewrite in your own words, and review on a schedule.', 'Many people collect notes and never open them again. Notes become useful when they are easy to capture, easy to find, and written in a form you can act on. A few small habits make that far more likely. Capture first, organize later Keep one inbox for quick notes, such as a single app or a pocket notebook. Do not stop to decide where something belongs. Once a day or a few times a week, empty the inbox and move each item to the right place or delete it. Rewrite in your own words Copying a quote is quick but passive. After reading something, write two or three sentences explaining it as if to a friend, and add one question or one way you could use it. This step takes a minute and is where most of the learning happens. Link notes to projects Organize by what you are working on instead of by topic. A note filed under a current project has a reason to be opened. Add a short title that states the idea, such as Shorter meetings need a written agenda, rather than a vague label. Review on a schedule Set a recurring ten-minute review each week. Skim recent notes, pull out any tasks, and archive what you no longer need. A small, regular review keeps the system useful without turning it into a hobby. Key takeaways Use one inbox and sort it on a schedule. Rewrite ideas in your own words. File notes by project and give them clear titles. Frequently asked questions Should I use paper or an app? Use whichever you will carry and open daily. Both can work well. How many notes is too many? If you cannot find what you need in a minute, prune and simplify your structure. This is sample content created to demonstrate the template. It is not professional advice.'),
  (6, 'A Gentle Start to Digital Minimalism', 'A sample guide to using technology on purpose: audit your apps, change defaults, and set simple limits.', 'Digital minimalism is the practice of choosing the tools that serve your goals and letting the rest go. You do not have to delete everything or move to a flip phone. Small changes to how you use your devices can free up a surprising amount of attention. Audit what you use For one week, notice which apps you open and how you feel afterward. Many devices show screen-time reports. Mark each app as useful, neutral, or draining. Remove the draining ones from your home screen, or uninstall them for a trial period of two weeks. Change the defaults Turn off notifications that are not from a person. Move social apps off the first screen. Switch the display to grayscale in the evening if your device allows it. Each change adds a little friction to mindless checking and takes a few minutes to set up. Set simple boundaries Choose one or two screen-free times, such as meals and the first half hour of the morning. Charge your phone away from the bed. Replace the habit with something specific, like a short walk or a few pages of a book, so the gap does not feel empty. After a few weeks, add back only the tools that earn their place. Key takeaways Audit apps by how they make you feel. Turn off notifications from non-people. Pick one or two screen-free times and replace them with something specific. Frequently asked questions Do I have to quit social media? No. You can keep it while limiting when and how you use it. How long should a trial last? Two to four weeks is enough to see how you feel without a given app. This is sample content created to demonstrate the template. It is not professional advice.');
