// Generates neutral brand assets from the site name (monogram of its initial):
//  - public/favicon.svg, icon-192.svg, icon-512.svg
//  - public/favicon.ico, apple-touch-icon.png, icon-192.png, icon-512.png
//  - public/manifest.json
// The OG image is generated by scripts/gen-og.mjs.
//   SITE_NAME="My Site" node scripts/gen-assets.mjs     (default "Edge Magazine")
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Resvg } from "@resvg/resvg-js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SITE_NAME = (process.env.SITE_NAME || "Edge Magazine").trim();
const INITIAL = ([...SITE_NAME][0] || "E").toUpperCase();
const INK = "#111111";
const PAPER = "#f8f8f6";
const ACCENT = "#d9291b";
const SERIF = "'Playfair Display', Georgia, 'Times New Roman', serif";

const esc = (s) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

// Monogram in a 100x100 box: ink rounded tile, paper initial, small accent dot.
function monogram(x, y, size) {
  const s = size / 100;
  return `<g transform="translate(${x} ${y}) scale(${s})">
    <rect width="100" height="100" rx="22" fill="${INK}"/>
    <text x="50" y="50" dy="0.35em" text-anchor="middle" font-family="${SERIF}" font-size="68" font-weight="800" fill="${PAPER}">${esc(INITIAL)}</text>
    <circle cx="80" cy="80" r="6" fill="${ACCENT}"/>
  </g>`;
}

function faviconSvg() {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 100 100">
  ${monogram(0, 0, 100)}
</svg>`;
}

// App icon: monogram centered on a Paper tile.
function appIconSvg(size) {
  const mark = Math.round(size * 0.72);
  const off = Math.round((size - mark) / 2);
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
  <rect width="${size}" height="${size}" rx="${Math.round(size * 0.16)}" fill="${PAPER}"/>
  ${monogram(off, off, mark)}
</svg>`;
}

// Raster favicon / touch icon source: full-bleed Paper tile (no transparency,
// iOS fills transparent regions with black).
function iconTileSvg(size, markRatio) {
  const mark = Math.round(size * markRatio);
  const off = Math.round((size - mark) / 2);
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
  <rect width="${size}" height="${size}" fill="${PAPER}"/>
  ${monogram(off, off, mark)}
</svg>`;
}

function renderPng(svg, size) {
  const resvg = new Resvg(svg, {
    fitTo: { mode: "width", value: size },
    font: { loadSystemFonts: true, defaultFontFamily: "Georgia" },
  });
  return resvg.render().asPng();
}

// Build a .ico container from PNG-encoded entries (PNG-in-ICO is supported by
// every browser that still requests /favicon.ico, and by Google's crawler).
function icoFromPngs(entries) {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0); // reserved
  header.writeUInt16LE(1, 2); // type: icon
  header.writeUInt16LE(entries.length, 4);
  const dir = Buffer.alloc(16 * entries.length);
  let offset = header.length + dir.length;
  entries.forEach(({ size, png }, i) => {
    const o = i * 16;
    dir.writeUInt8(size >= 256 ? 0 : size, o); // width (0 means 256)
    dir.writeUInt8(size >= 256 ? 0 : size, o + 1); // height
    dir.writeUInt8(0, o + 2); // color palette
    dir.writeUInt8(0, o + 3); // reserved
    dir.writeUInt16LE(1, o + 4); // color planes
    dir.writeUInt16LE(32, o + 6); // bits per pixel
    dir.writeUInt32LE(png.length, o + 8);
    dir.writeUInt32LE(offset, o + 12);
    offset += png.length;
  });
  return Buffer.concat([header, dir, ...entries.map((e) => e.png)]);
}

function write(path, content) {
  const full = join(ROOT, path);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, content);
}

write("public/favicon.svg", faviconSvg());
write("public/icon-192.svg", appIconSvg(192));
write("public/icon-512.svg", appIconSvg(512));

// Raster icons for the fixed paths browsers request directly.
write(
  "public/favicon.ico",
  icoFromPngs(
    [16, 32, 48].map((size) => ({
      size,
      png: renderPng(iconTileSvg(size, 0.9), size),
    })),
  ),
);
write("public/apple-touch-icon.png", renderPng(iconTileSvg(180, 0.78), 180));
write("public/icon-192.png", renderPng(appIconSvg(192), 192));
write("public/icon-512.png", renderPng(appIconSvg(512), 512));

write(
  "public/manifest.json",
  JSON.stringify(
    {
      name: SITE_NAME,
      short_name: SITE_NAME,
      description: "An independent editorial magazine",
      lang: "en",
      start_url: "/",
      display: "standalone",
      background_color: PAPER,
      theme_color: INK,
      icons: [
        { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
        { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
        { src: "/icon-512.svg", sizes: "any", type: "image/svg+xml" },
      ],
    },
    null,
    2,
  ) + "\n",
);

console.log(`Generated brand assets for "${SITE_NAME}" (initial "${INITIAL}").`);
